config/routes.rb
G5jedi::Application.routes.draw do
  resources :links

  resources :difficulties

  root :to => 'topics#index'

  resources :topics

  resources :ranks

  resources :questions

  resources :quizzes do
    resources :questions do
      resources :question_choices
    end
  end
end

app/models/difficulty.rb
class Difficulty < ActiveRecord::Base
  has_many :quizzes
  has_many :questions
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :difficulty
  belongs_to :topic
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates_presence_of :text
  validates_uniqueness_of :text
  belongs_to :quiz
  has_many :question_choices
  belongs_to :difficulty
  accepts_nested_attributes_for :question_choices
end

app/models/question_choice.rb
class QuestionChoice < ActiveRecord::Base
  belongs_to :question
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
  validates_presence_of :title
  belongs_to :topic
  has_many :questions
  has_one :difficulty
end

app/models/rank.rb
class Rank < ActiveRecord::Base
  has_many :topics
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :rank
  has_many :quizzes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/difficulties_controller.rb
class DifficultiesController < ApplicationController
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
end

app/controllers/question_choices_controller.rb
class QuestionChoicesController < InheritedResources::Base
  belongs_to :quiz
  belongs_to :question
end

app/controllers/questions_controller.rb
class QuestionsController < InheritedResources::Base
  belongs_to :quiz

  def index
    if params[:quiz_id]
      @questions = Quiz.find(params[:quiz_id]).questions
    else
      @questions = Question.all
    end
  end

  def new
    @question = Question.new
    @quizzes = Quiz.all
    @difficulties = Difficulty.all
    4.times {@question.question_choices.build}
  end

  def create
    @question = Question.new(params[:question])
    if @question.save
      redirect_to "/quizzes/#{@question.quiz_id}/questions/new", :notice => "Question '#{@question.text}' successfully created"
    else
      redirect_to :action => 'new'
    end
  end

  def edit
    @question = Question.find(params[:id])
    @quizzes = Quiz.all
    @difficulties = Difficulty.all
    params[:difficulty_id] = @question.difficulty.id unless @question.difficulty.nil?
    params[:quiz_id] = @question.quiz.id
  end

  def update
    @question = Question.find(params[:id])
    @question.attributes = params[:question]
    @question.save
    redirect_to :action => 'index'
  end

  def destroy
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def index
    @quizzes = Quiz.all
  end

  def show
    @quiz = Quiz.find(params[:id])
  end

  def new
    @quiz = Quiz.new
    @quizzes = Quiz.all
    @question = Question.new
    @topics = Topic.all
  end

  def create
    @quiz = Quiz.new(params[:quiz])
    if @quiz.save
      redirect_to(:action => 'index', :notice => 'Quiz was successfully created.')
    else
      render :action => 'new'
    end
  end

  def edit
    @quiz = Quiz.find(params[:id])
    @topics = Topic.all
    params[:topic_id] = @quiz.topic.id unless @quiz.topic.nil?
  end

  def update
  end

  def destroy
  end
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  def index
    @ranks = Rank.all
  end

  def new
    @rank = Rank.new
  end

  def create
    @rank = Rank.new(params[:rank])
    if @rank.save
      redirect_to(:action => 'index', :notice => 'Rank was successfully created.')
    else
      render :action => 'new'
    end
  end

  def update
  end

  def destroy
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
    @topics.sort_by!{|t| t.order}
    @ranks = Rank.all
  end

  def new
    @topic = Topic.new
    @ranks = Rank.all
  end

  def create
    @topic = Topic.new(params[:topic])
    if Topic.first
      @topic.order = Topic.all.max_by{|t| t.order}.order+1
    else
      @topic.order = 1
    end
    if @topic.save
      redirect_to(:action => 'index', :notice => 'Topic was successfully created.')
    else
      render :action => 'new'
    end
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/difficulties_helper.rb
module DifficultiesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/question_choices_helper.rb
module QuestionChoicesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/links/_form.html.erb
<% form_for (@link) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br/>
  <%= f.label :url %>
  <%= f.text_field :url %><br/>
<% end %>

app/views/questions/_form.html.erb
<% form_for (@question) do |f| %>
  <%= f.label :text, 'Question' %>
  <%= f.text_field :text %><br/>
  <%= f.label :quiz_id, "Quiz:" %>
  <%= f.select(:quiz_id, options_for_select(@quizzes.collect {|q| [q.title, q.id]}, params[:quiz_id])) %><br/>
  <%= f.label :difficulty_id, "Difficulty:" %>
  <%= f.select(:difficulty_id, options_for_select(@difficulties.collect {|d| [d.name, d.id]}, params[:difficulty_id])) %><br/>

  <% f.fields_for :question_choices do |qc| %>
    <%= qc.label :text, "Answer: " %>
    <%= qc.text_field :text %>
    <%= qc.check_box :correct %><br/>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/questions/edit.html.erb
<%= render 'form' %>

app/views/questions/index.html.erb
<% @questions.each do |question| %>
  <h3 class="question">
    <%= question.text %> <%= "(#{question.difficulty.name})" if question.difficulty %>
    <%= link_to 'Edit Question', edit_question_path(question) %>
  </h3>
  <ul class="question_choices">
    <% question.question_choices.each do |choice| %>
      <li><%= choice.text %> <%= '(Correct)' if choice.correct %></li>
    <% end %>
  </ul>
<% end %>

app/views/questions/new.html.erb
<%= flash[:notice] %>
<%= render 'form' %>

app/views/ranks/_form.html.erb
<%= form_for (@rank) do |f| %>
  Name: <%= f.text_field :name %>
  Description: <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/ranks/index.html.erb
<h1>Ranks</h1>
<%= link_to 'New', :action => 'new' %><br/>
<% @ranks.each do |rank| %>
  <%= rank.name %>: 
  <%= rank.description %><br/>
<% end %>

app/views/topics/_form.html.erb
<%= form_for (@topic) do |f| %>
  Name: <%= f.text_field :name %>
  Description: <%= f.text_field :description %><br/>
  <%= f.select(:rank_id, options_for_select(@ranks.collect {|r| [r.name, r.id]}, params[:rank_id])) %>
  <%= f.submit %>
<% end %>

app/views/topics/index.html.erb
<h1>Topics</h1>
<%= link_to 'New', :action => 'new' %><br/>
<% @ranks.each do |rank| %>
  <h2><%= rank.name %></h2>
  <h5><%= rank.description %></h5>
  <% rank.topics.sort_by{|t| t.order}.each do |topic| %>
    <%= topic.name %>: 
    <%= topic.description %><br/>
  <% end %>
<% end %>